name: mybatis
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken 2FT5RCjFBjuxX7HnC7FkrVESZ5K_3dvYDeFCvfv9x9mK9u7Ff
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: China Time UTC+8
      run: tzutil /s "China Standard Time"
    - name: set region in china
      run: Set-WinSystemLocale zh-cn
    - name: Download d4time.msi to destop
      run: Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/d4time531.msi -OutFile "C:\Users\runneradmin\Desktop\d4time531.msi"
    - name: Download InternetDownloadManager to destop
      run: Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/IDM64220231218.exe -OutFile "C:\Users\runneradmin\Desktop\IDM.exe"
    - name: Download IDMACT to destop
      run: Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/IDMACT.cmd -OutFile "C:\Users\runneradmin\Desktop\IDMACT.cmd"
    - name: Download netspeedmonitor_2_5_4_0_x64_setup.msi to destop
      run: Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/netspeedmonitor_2_5_4_0_x64_setup.msi -OutFile "C:\Users\runneradmin\Desktop\netspeedmonitor_2_5_4_0_x64_setup.msi"
    - name: Download winrar-x64-623sc.exe to destop
      run: Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/winrar-x64-623sc.exe -OutFile "C:\Users\runneradmin\Desktop\winrar-x64-623sc.exe"
    - name: Download ChromeSetup.exe to destop
      run: Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/ChromeSetup.exe -OutFile "C:\Users\runneradmin\Desktop\ChromeSetup.exe"
    - name: Download exportucloudurls2023.txt to destop
      run: Invoke-WebRequest https://storage.googleapis.com/staging.oscar-project-2023.appspot.com/VPS/exportucloudurls2023.txt -OutFile "C:\Users\runneradmin\Desktop\exportucloudurls2023.txt"
    - name: Download gugeliulanqi to destop
      run: Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/gugeliulanqi64.exe -OutFile "C:\Users\runneradmin\Desktop\gugeliulanqi64.exe"
    - name: Download AIREXPLORER drive manager cracked 4.0.1 Version to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/AE4P0P1CRACKED.zip -OutFile "C:\Users\runneradmin\Desktop\AE4P0P1CRACKED.zip"
    - name: Download AIREXPLORER drive manager Accounts Config File to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/AEEXPLORERACCOUNTS20231125.airexp -OutFile "C:\Users\runneradmin\Desktop\AEEXPLORERACCOUNTS20231125.airexp"
    - name: Download 5in1script.reg to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/5in1script.reg -OutFile "C:\Users\runneradmin\Desktop\5in1script.reg"
    - name: Download UCLOUDSTORAGEACCOUNTS20231223.xml to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/UCLOUDSTORAGEACCOUNTS20231223.xml -OutFile "C:\Users\runneradmin\Desktop\UCLOUDSTORAGEACCOUNTS20231223.xml"
    - name: Download S3BROWSER.exe to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/S3BROWSER.exe -OutFile "C:\Users\runneradmin\Desktop\S3BROWSER.exe"
    - name: Download UCLOUDSTORAGEACCOUNTS20231223.xml to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/UCLOUDSTORAGEACCOUNTS20231223.xml -OutFile "C:\Users\runneradmin\Desktop\UCLOUDSTORAGEACCOUNTS20231223.xml"
    - name: Download volmaxbright60percent.bat to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/volmaxbright60percent.bat -OutFile "C:\Users\runneradmin\Desktop\volmaxbright60percent.bat"
    - name: Download volmaxbright60percentwaitsometime.bat to desktop
      run : Invoke-WebRequest https://storage.googleapis.com/oscar-project-2023.appspot.com/VPS/volmaxbright60percentwaitsometime.bat -OutFile "C:\Users\runneradmin\Desktop\volmaxbright60percentwaitsometime.bat"
    - name: Download chromedirectcutoffwindows.zip to desktop
      run : Invoke-WebRequest https://s3-cn-bj.ufileos.com/cloudshell-0132393dc9/oscar2023/chromedirectcutoffwindows.zip -Outfile "C:\Users\runneradmin\Desktop\chromedirectcutoffwindows.zip"
    - name: show seconds in system clock
      run: reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowSecondsInSystemClock /t REG_DWORD /d 1
    - name: taskkill explorer.exe
      run: taskkill /im explorer.exe /F
    - name: start explorer.exe
      run: start explorer.exe
    - name: start taskmgr.exe
      run: start taskmgr.exe
    - name: set systemlocaleinchinapowershell
      run: Set-WinSystemLocale zh-cn
      shell: powershell
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 5
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Test12345678" -Force)
    - name: Start Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
